/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xo

import xo.board.Board

class App
fun main() {
    val board = Board()
    board.mark(4, 'X')
    board.mark(3, 'O')
    board.display()
}
